apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: test
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http"]
    # defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      # [entryPoints.http.redirect]
      # entryPoint = "https"
      # [entryPoints.https.auth.basic]
      # users = ["klefevre:$apr1$k2qslCn6$0OgA8vhnyC8nJ99YfJMOM/"]
      # [entryPoints.https]
      # address = ":443"
      # [entryPoints.https.tls]
    # [acme]
    # email = "info@scoutlit.com"
    # storageFile = "/acme/acme.json"
    # entryPoint = "https"
    # onDemand = true
    # onHostRule = true
    # caServer = "https://acme-staging.api.letsencrypt.org/directory"
    # [[acme.domains]]
    # main = "archifleks.net"
    [kubernetes]
      namespaces = ["test"]