kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: accounts-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounts-persistent-storage-claim
  labels:
    app: accounts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  type: LoadBalancer
  selector:
    app: accounts
    role: api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  selector:
    matchLabels:
      app: accounts
      role: api
  replicas: 3
  template:
    metadata:
      labels:
        app: accounts
        role: api
    spec:
      containers:
        - name: accounts-api
          image: gcr.io/ncci-k8s/accounts-service
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
            - name: DB_URL
              value: "mongodb://accounts-db:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-db
spec:
  type: ClusterIP
  selector:
    app: accounts
    role: database
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-db
spec:
  selector:
    matchLabels:
      app: accounts
      role: database
  replicas: 1
  template:
    metadata:
      labels:
        app: accounts
        role: database
    spec:
      containers:
        - name: accounts-mongo
          image: mongo:4.0
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: accounts-persistent-storage
              mountPath: /data/db
      volumes:
        - name: accounts-persistent-storage
          persistentVolumeClaim:
            claimName: accounts-persistent-storage-claim

  # volumeClaimTemplates:
  # - metadata:
  #     name: accounts-persistent-storage
  #     annotations:
  #       volume.beta.kubernetes.io/storage-class: "accounts-storage"
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 3Gi


