kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: users-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-persistent-storage-claim
  labels:
    app: users
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  type: LoadBalancer
  selector:
    app: users
    role: api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  selector:
    matchLabels:
      app: users
      role: api
  replicas: 3
  template:
    metadata:
      labels:
        app: users
        role: api
    spec:
      containers:
        - name: users-api
          image: gcr.io/ncci-k8s/users-service
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
            - name: DB_URL
              value: "mongodb://users-db:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: users-db
spec:
  type: ClusterIP
  selector:
    app: users
    role: database
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db
spec:
  selector:
    matchLabels:
      app: users
      role: database
  replicas: 1
  template:
    metadata:
      labels:
        app: users
        role: database
    spec:
      containers:
        - name: users-mongo
          image: mongo:4.0
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: users-persistent-storage
              mountPath: /data/db
      volumes:
        - name: users-persistent-storage
          persistentVolumeClaim:
            claimName: users-persistent-storage-claim