kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: accounts-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-mongo
  labels:
    name: accounts-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
    app: accounts
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: accounts-mongo
spec:
  serviceName: "accounts-mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        app: accounts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: accounts-mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: accounts-persistent-storage
              mountPath: /data/db
        - name: accounts-mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,app=accounts"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: "accounts-mongo"
  volumeClaimTemplates:
  - metadata:
      name: accounts-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "accounts-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  type: LoadBalancer
  selector:
    role: api
    app: accounts
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    role: api
    app: accounts
spec:
  replicas: 2
  selector:
    matchLabels:
      role: api
      app: accounts
  template:
    metadata:
      labels:
        role: api
        app: accounts
    spec:
      containers:
      - name: accounts-api
        image: gcr.io/ncci-k8s/accounts-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            value: accounts-mongo-0.accounts-mongo